In [10]:
import numpy as np 
import pandas as pd

In [23]:
peliculas = pd.read_csv('data/tmdb_10000_movies.csv')

In [24]:
peliculas.head(2)

,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,385687,Rápidos y furiosos X,2023-05-17,"['Action', 'Crime', 'Thriller']",English,7.4,1347.0,8363.473,Over many missions and against impossible odds...,340000000.0,"['Universal Pictures', 'Original Film', 'One R...",652000000.0,142.0,The end of the road begins.
1,603692,John Wick 4,2023-03-22,"['Action', 'Thriller', 'Crime']",English,7.9,2896.0,4210.313,"With the price on his head ever increasing, Jo...",90000000.0,"['Thunder Road', '87Eleven', 'Summit Entertain...",431769198.0,170.0,"No way back, one way out."

In [26]:
peliculas.describe()

,id,vote_average,vote_count,popularity,budget,revenue,runtime
count,1.000100e+04,10000.000000,10000.000000,10000.000000,9.999000e+03,9.999000e+03,9999.000000
mean,3.001465e+05,6.319090,1558.294800,33.542340,1.993800e+07,6.084337e+07,100.809581
std,3.379901e+05,1.460605,2887.861217,126.495621,3.870582e+07,1.553073e+08,27.850165
min,0.000000e+00,0.000000,0.000000,12.297000,0.000000e+00,0.000000e+00,0.000000
25%,1.150400e+04,5.900000,143.000000,14.599000,0.000000e+00,0.000000e+00,90.000000
50%,1.184060e+05,6.600000,519.000000,18.582500,1.250000e+06,2.133452e+06,100.000000
75%,5.379150e+05,7.100000,1584.000000,28.014500,2.300000e+07,5.106230e+07,115.000000
max,1.136631e+06,10.000000,33822.000000,8363.473000,4.600000e+08,2.923706e+09,366.000000

In [27]:
peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10001 non-null  int64
 1   title                 10001 non-null  object
 2   release_date          9978 non-null   object
 3   genres                10001 non-null  object
 4   original_language     10000 non-null  object
 5   vote_average          10000 non-null  float64
 6   vote_count            10000 non-null  float64
 7   popularity            10000 non-null  float64
 8   overview              9924 non-null   object
 9   budget                9999 non-null   float64
 10  production_companies  9999 non-null   object
 11  revenue               9999 non-null   float64
 12  runtime               9999 non-null   float64
 13  tagline               7383 non-null   object
dtypes: float64(6), int64(1), object(7)
memory usage: 1.1+ MB

In [28]:
peliculas.isnull().sum()

id                         0
title                      0
release_date              23
genres                     0
original_language          1
vote_average               1
vote_count                 1
popularity                 1
overview                  77
budget                     2
production_companies       2
revenue                    2
runtime                    2
tagline                 2618
dtype: int64

In [29]:
peliculas.columns

Index(['id', 'title', 'release_date', 'genres', 'original_language',
       'vote_average', 'vote_count', 'popularity', 'overview', 'budget',
       'production_companies', 'revenue', 'runtime', 'tagline'],
      dtype='object')

In [31]:
peliculas=peliculas[['id', 'title', 'overview', 'genres']]

In [32]:
peliculas

,id,title,overview,genres
0,385687,Rápidos y furiosos X,Over many missions and against impossible odds...,"['Action', 'Crime', 'Thriller']"
1,603692,John Wick 4,"With the price on his head ever increasing, Jo...","['Action', 'Thriller', 'Crime']"
2,502356,Super Mario Bros. La película,"While working underground to fix a water main,...","['Animation', 'Family', 'Adventure', 'Fantasy'..."
3,569094,Spider-Man: A través del Spider-Verso,"After reuniting with Gwen Stacy, Brooklyn’s fu...","['Action', 'Adventure', 'Animation', 'Science ..."
4,536437,Hipnosis: Arma Invisible,A detective becomes entangled in a mystery inv...,"['Mystery', 'Thriller', 'Science Fiction']"
...,...,...,...,...
9996,33142,Vivah: Amor a prueba de fuego,"Poonam, a traditionally brought-up young woman...","['Romance', 'Drama']"
9997,9442,El Cliente Muerto No Paga,Juliet Forrest is convinced that the reported ...,"['Comedy', 'Mystery']"
9998,28774,Comunión,A novelist's wife and son see him changed by a...,"['Drama', 'Horror', 'Science Fiction', 'Thrill..."
9999,11121,Tess,A strong-willed peasant girl is sent by her fa...,"['Drama', 'Romance']"
10000,272692,La posesion de Michel King,The film tells the story of documentary filmma...,['Horror']

In [35]:
peliculas['tags'] = peliculas['overview']+peliculas['genres']

C:\Users\harvi\AppData\Local\Temp\ipykernel_9960\1341426971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peliculas['tags'] = peliculas['overview']+peliculas['genres']

In [36]:
peliculas

,id,title,overview,genres,tags
0,385687,Rápidos y furiosos X,Over many missions and against impossible odds...,"['Action', 'Crime', 'Thriller']",Over many missions and against impossible odds...
1,603692,John Wick 4,"With the price on his head ever increasing, Jo...","['Action', 'Thriller', 'Crime']","With the price on his head ever increasing, Jo..."
2,502356,Super Mario Bros. La película,"While working underground to fix a water main,...","['Animation', 'Family', 'Adventure', 'Fantasy'...","While working underground to fix a water main,..."
3,569094,Spider-Man: A través del Spider-Verso,"After reuniting with Gwen Stacy, Brooklyn’s fu...","['Action', 'Adventure', 'Animation', 'Science ...","After reuniting with Gwen Stacy, Brooklyn’s fu..."
4,536437,Hipnosis: Arma Invisible,A detective becomes entangled in a mystery inv...,"['Mystery', 'Thriller', 'Science Fiction']",A detective becomes entangled in a mystery inv...
...,...,...,...,...,...
9996,33142,Vivah: Amor a prueba de fuego,"Poonam, a traditionally brought-up young woman...","['Romance', 'Drama']","Poonam, a traditionally brought-up young woman..."
9997,9442,El Cliente Muerto No Paga,Juliet Forrest is convinced that the reported ...,"['Comedy', 'Mystery']",Juliet Forrest is convinced that the reported ...
9998,28774,Comunión,A novelist's wife and son see him changed by a...,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",A novelist's wife and son see him changed by a...
9999,11121,Tess,A strong-willed peasant girl is sent by her fa...,"['Drama', 'Romance']",A strong-willed peasant girl is sent by her fa...
10000,272692,La posesion de Michel King,The film tells the story of documentary filmma...,['Horror'],The film tells the story of documentary filmma...

In [39]:
datos_nuevos  = peliculas.drop(columns=['overview', 'genres'])

In [40]:
datos_nuevos

,id,title,tags
0,385687,Rápidos y furiosos X,Over many missions and against impossible odds...
1,603692,John Wick 4,"With the price on his head ever increasing, Jo..."
2,502356,Super Mario Bros. La película,"While working underground to fix a water main,..."
3,569094,Spider-Man: A través del Spider-Verso,"After reuniting with Gwen Stacy, Brooklyn’s fu..."
4,536437,Hipnosis: Arma Invisible,A detective becomes entangled in a mystery inv...
...,...,...,...
9996,33142,Vivah: Amor a prueba de fuego,"Poonam, a traditionally brought-up young woman..."
9997,9442,El Cliente Muerto No Paga,Juliet Forrest is convinced that the reported ...
9998,28774,Comunión,A novelist's wife and son see him changed by a...
9999,11121,Tess,A strong-willed peasant girl is sent by her fa...
10000,272692,La posesion de Michel King,The film tells the story of documentary filmma...

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [55]:

cv=CountVectorizer(max_features=10000, stop_words='english')

In [56]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [57]:
vector=cv.fit_transform(datos_nuevos['tags'].values.astype('U')).toarray()

In [58]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity=cosine_similarity(vector)

similarity

array([[1.        , 0.12555296, 0.05884899, ..., 0.04688072, 0.        ,
        0.        ],
       [0.12555296, 1.        , 0.03232541, ..., 0.05150262, 0.        ,
        0.        ],
       [0.05884899, 0.03232541, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.04688072, 0.05150262, 0.        , ..., 1.        , 0.07161149,
        0.070447  ],
       [0.        , 0.        , 0.        , ..., 0.07161149, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.070447  , 0.        ,
        1.        ]])

In [91]:
datos_nuevos[datos_nuevos['title']=="La Era de Hielo: Las aventuras de Buck"].index[0]

289

In [92]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(datos_nuevos.iloc[i[0]].title)

Super Mario Bros. La película
Unidos
La Era de Hielo: Las aventuras de Buck
Super Mario Bros.
スーパーマリオブラザーズ ピーチ姫救出大作戦!

In [78]:
def recommand(movies):
    index=datos_nuevos[datos_nuevos['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(datos_nuevos.iloc[i[0]].title)

In [90]:
recommand("Sangre y oro")

Sangre y oro
La batalla de Midway
Ocho a la deriva
El Bombardeo
Viviendo con El enemigo

In [83]:
import pickle

In [87]:
pickle.dump(datos_nuevos, open('ListaDePelis.pkl', 'wb'))

In [88]:
pickle.dump(similarity, open('Similitudes.pkl', 'wb'))

In [89]:
pickle.load(open('ListaDePelis.pkl', 'rb'))

,id,title,tags
0,385687,Rápidos y furiosos X,Over many missions and against impossible odds...
1,603692,John Wick 4,"With the price on his head ever increasing, Jo..."
2,502356,Super Mario Bros. La película,"While working underground to fix a water main,..."
3,569094,Spider-Man: A través del Spider-Verso,"After reuniting with Gwen Stacy, Brooklyn’s fu..."
4,536437,Hipnosis: Arma Invisible,A detective becomes entangled in a mystery inv...
...,...,...,...
9996,33142,Vivah: Amor a prueba de fuego,"Poonam, a traditionally brought-up young woman..."
9997,9442,El Cliente Muerto No Paga,Juliet Forrest is convinced that the reported ...
9998,28774,Comunión,A novelist's wife and son see him changed by a...
9999,11121,Tess,A strong-willed peasant girl is sent by her fa...
10000,272692,La posesion de Michel King,The film tells the story of documentary filmma...